### PR TITLE
Accelerate table compaction

### PR DESCRIPTION
**Pull request by qianbin**
This PR introduces async iterator and async writer, which wrap iterator.Iterator and storage.Writer, to accelerate table compaction process.

### CODE REVIEW

**Comment by qianbin** [comment]
Rough bechmarks on 13' MacBook Pro 2018

with options 
```
BlockCacheCapacity: 256 * opt.MiB,
WriteBuffer:        opt.MiB * 128,
Filter:                   filter.NewBloomFilter(10),
```
write 50,000,000 random kv pairs 
key size = 100B
value size = 100B
total size = 10GB

* master
```
Total time: 10m17.648834594s
Cumulative compaction time: 8m17.506521s
```

* this PR
```
Total time: 7m29.826281807s
Cumulative compaction time: 5m39.507442s
```

**Comment by qianbin** [comment]
by applying the last commit
```
Total time: 6m38.339845088s
Cumulative compaction time: 4m47.883195s
```

**Comment by fxfactorial** [comment]
@qianbin did you ever use this in production?

**Comment by qianbin** [comment]
@fxfactorial yes.

**Pull request closed without merging**
