### PR TITLE
Add full support for WebAssembly in both browser and Node.js environments

### PR DESCRIPTION
**Pull request by albrow**
This PR expands on #277 (which supported Node.js only) and adds support for running `goleveldb` in the browser. This is accomplished by using [BrowserFS](https://github.com/jvilk/BrowserFS) and writing `syscall/js` bindings that mimic the functions and methods in the Go standard library. AFAIK there is no way for us to embed BrowserFS, so users will need to include and initialize it separately (typically inside of a script tag prior to loading the WebAssembly bytecode).

This PR also includes a mechanism for running a small set of tests in a headless browser by simply running `go test` a the repository root. These tests require Node.js and `npm`.

@syndtr if this is something you are interested in, we would love to get it merged upstream so that other people could make use of it. I imagine we will need to add some more documentation specifically around browser support. I also anticipate that you might want to tweak some things about the file structure, naming conventions, and how browser tests are run. Let me know if you have any questions or if there is anything I can do to help.

### CODE REVIEW

**Comment by albrow** [comment]
The browser tests pass locally but I'm having some difficulty getting them to work in CI. There are a couple of issues:

- Versions of Go < 1.11 don't support Go Modules so they are unable to find and download our QUnit bindings, which the browser tests depend on.
- Go version 1.11 uses a different API for the `syscall/js` package, which is used to call out to JavaScript code. I wrote the bindings with Go version 1.12 in mind.
- TravisCI seems to have some issues with running [puppeteer](https://github.com/GoogleChrome/puppeteer) (a headless Chrome browser used for the tests).

Any ideas about how to address these? It would be nice if the tests could run in CI to make sure that browser support doesn't break in the future.

**Comment by albrow** [comment]
I just pushed a few more commits which allow support for [asynchronous BrowserFS backends](https://github.com/jvilk/BrowserFS/blob/master/src/DOCS.md#overview-of-backends) (i.e. those that don't have support for functions with the `Sync` suffix).

For 0x Mesh we are using BrowserFS backed by IndexedDB. You can see [this PR](https://github.com/0xProject/0x-mesh/pull/533) for more context.

**Comment by goldbock** [comment]
any update on this? go-ethereum fails to compile to wasm due the  lack of support of wasm target by go-leveldb.

**Comment by simbadMarino** [comment]
@syndtr , any plans to merge this? Would be great to have Wasm support =)

**Comment by simbadMarino** [comment]
hello @albrow , I'm using your commit from 0xProject in the mean time by replacing in my go.mod, however I'm getting the following errors during build:
image

Any ideas on what I'm missing or what could be happening? Thanks

**Comment by albrow** [comment]
@simbadMarino I haven't worked with Go and WebAssembly in a few years. The `syscall/js` package was always marked as "experimental" and it looks like some things may have changed under the hood since I originally wrote that code. It would probably not be too difficult to update if you take a look at the latest documentation for `syscall/js`: https://pkg.go.dev/syscall/js.

**Comment by simbadMarino** [comment]
> @simbadMarino I haven't worked with Go and WebAssembly in a few years. The `syscall/js` package was always marked as "experimental" and it looks like some things may have changed under the hood since I originally wrote that code. It would probably not be too difficult to update if you take a look at the latest documentation for `syscall/js`: https://pkg.go.dev/syscall/js.

Thanks for the quick reply! let me dig a bit into it :), will keep you posted

EDIT: Most likely something in either of these commits broke something:

https://github.com/golang/go/commit/cd5309355e25dda4a33bcf5c931aae5a15f9de94
https://github.com/golang/go/commit/2bd767b1022dd3254bcec469f0ee164024726486

**Comment by simbadMarino** [comment]
> > @simbadMarino I haven't worked with Go and WebAssembly in a few years. The `syscall/js` package was always marked as "experimental" and it looks like some things may have changed under the hood since I originally wrote that code. It would probably not be too difficult to update if you take a look at the latest documentation for `syscall/js`: https://pkg.go.dev/syscall/js.
> 
> Thanks for the quick reply! let me dig a bit into it :), will keep you posted
> 
> EDIT: Most likely something in either of these commits broke something:
> 
> [golang/go@cd53093](https://github.com/golang/go/commit/cd5309355e25dda4a33bcf5c931aae5a15f9de94) [golang/go@2bd767b](https://github.com/golang/go/commit/2bd767b1022dd3254bcec469f0ee164024726486)

I managed to fix it by using reflect to compare, if anyone is interested I created a fork which compiles wasm successfully on go v1.19.9: https://github.com/simbadMarino/goleveldb. Thanks!

**Comment by v1rtl** [comment]
@simbadMarino I'm unable to install your fork:

```
go: github.com/simbadMarino/goleveldb@upgrade (v1.1.2) requires github.com/simbadMarino/goleveldb@v1.1.2: parsing go.mod:
        module declares its path as: github.com/syndtr/goleveldb
                but was required as: github.com/simbadMarino/goleveldb
```

Using a `replace` leads to this error:

```
github.com/syndtr/goleveldb requires github.com/0xProject/qunit
BUT
github.com/0xProject/qunit does not exist anymore (404 Not Found).
```

**Comment by simbadMarino** [comment]
hey @talentlessguy , please try again, I just updated the qunit dep and module name, seems like 0xProject decided to completely wipe their qunit repo, I changed the source code and now pointing to rusco's , reference: https://ethereum.stackexchange.com/questions/127894/was-0xproject-goleveldb-qunit-discontinued

let me know if you succeed building for webassy. I didn't run much tests after the update.

**Comment by v1rtl** [comment]
@simbadMarino it worked, thank you

BrowserFS though seems to have been deprecated in favor of ZenFS. Most likely that would need implementing separate support for it

**Comment by simbadMarino** [comment]
Thanks for testing @talentlessguy , I'll check on the ZenFS updates as well, probably someone already updated that in another fork. If not will try to update myself later on. Thanks for the heads up! 
Happy coding!

**Comment by v1rtl** [comment]
@simbadMarino I'm currently trying to add support for it myself in my own fork. my work also supports WASI as well (it doesn't rely on ZenFS)

**Comment by simbadMarino** [comment]
Fantastic ! I’ll keep an eye on it, I stopped my BTFS wasm development due to limited filesystem capabilities , probably your fork can help me moving forward @talentlessguy

**Pull request closed without merging**
